version: '3'
services:
  app:
    container_name: graph-test
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/opt/app
    ports:
      - 3000:3000
    expose:
      - '3000'
    env_file: 
      - .env
    networks:
      - graph-test
      - db-graph
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - graph_test_data:/var/lib/postgresql/data
    networks:
      - db-graph

volumes:
  graph_test_data:
networks: 
  graph-test: 
    external: true
  db-graph:
    external: false
